copy ..\classic_spell_icons\gemicons01.tga .
copy ..\classic_spell_icons\gemicons02.tga .
copy ..\classic_spell_icons\gemicons03.tga .
copy ..\classic_spell_icons\Spells01.tga .
copy ..\classic_spell_icons\Spells02.tga .
copy ..\classic_spell_icons\Spells03.tga .
copy ..\classic_spell_icons\Spells04.tga .
copy ..\classic_spell_icons\Spells05.tga .
copy ..\classic_spell_icons\Spells06.tga .
copy ..\classic_spell_icons\Spells07.tga .
